namespace KcdMp.Server.Observability;

public enum ServerObservableSeverity
{
    Debug = 0,
    Information = 1,
    Warning = 2,
    Error = 3,
}

public enum ServerObservableComponent
{
    Backend = 0,
    Session = 1,
    Networking = 2,
    Persistence = 3,
    ServerLifecycle = 4,
    ClientIntegration = 5,
}

public enum ServerObservableEventType
{
    ServerStarted = 0,
    ServerStopped = 1,
    SessionCreated = 2,
    SessionClosed = 3,
    SessionTimeout = 4,
    AuthenticationAccepted = 5,
    AuthenticationRejected = 6,
    AssociationPending = 7,
    BackendError = 8,
    PersistenceLoadCompleted = 9,
    PersistenceLoadFailed = 10,
    PersistenceSaveCompleted = 11,
    PersistenceSaveFailed = 12,
    IdentityResolved = 13,
    IdentityCreated = 14,
    IdentityAccessDenied = 15,
    IdentityStatusChanged = 16,
    CharacterCreated = 17,
    CharacterStatusChanged = 18,
    CharacterDeleted = 19,
    CharacterAccessDenied = 20,
    CharacterLoadStarted = 21,
    CharacterLoadCompleted = 22,
    CharacterLoadFailed = 23,
    CharacterSaveStarted = 24,
    CharacterSaveCompleted = 25,
    CharacterSaveFailed = 26,
    InventoryLoadStarted = 27,
    InventoryLoadCompleted = 28,
    InventoryLoadFailed = 29,
    InventorySaveStarted = 30,
    InventorySaveCompleted = 31,
    InventorySaveFailed = 32,
    InventoryChanged = 33,
    InventoryValidationFailed = 34,
    CurrencyLoadStarted = 35,
    CurrencyLoadCompleted = 36,
    CurrencyLoadFailed = 37,
    CurrencySaveStarted = 38,
    CurrencySaveCompleted = 39,
    CurrencySaveFailed = 40,
    CurrencyChanged = 41,
    CurrencyValidationFailed = 42,
    RespawnLoadStarted = 43,
    RespawnLoadCompleted = 44,
    RespawnLoadFailed = 45,
    RespawnSaveStarted = 46,
    RespawnSaveCompleted = 47,
    RespawnSaveFailed = 48,
    DefeatDetected = 49,
    UnconsciousEntered = 50,
    HealerRecoveryApplied = 51,
    UnconsciousExpired = 52,
    UnconsciousCancelled = 53,
    RespawnApplied = 54,
    RespawnApplyFailed = 55,
    InventoryRulesConfigLoaded = 56,
    InventoryRulesConfigValidationFailed = 57,
    InventoryRuleApplied = 58,
    InventoryLootabilityChanged = 59,
    InventoryRuleApplyFailed = 60,
}

public sealed record ServerObservableEvent(
    ServerObservableEventType Type,
    ServerObservableComponent Component,
    ServerObservableSeverity Severity,
    DateTimeOffset OccurredAtUtc,
    Guid? SessionId = null,
    string? IdentityId = null,
    string? CharacterId = null,
    string? Message = null,
    IReadOnlyDictionary<string, object?>? Payload = null);

